var annotated_dup =
[
    [ "ActionCommand", "struct_action_command.html", "struct_action_command" ],
    [ "ArtifactMachine", "class_artifact_machine.html", "class_artifact_machine" ],
    [ "AudioManager", "class_audio_manager.html", "class_audio_manager" ],
    [ "BattleController", "class_battle_controller.html", "class_battle_controller" ],
    [ "BattleEvent", "struct_battle_event.html", "struct_battle_event" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "Character", "class_character.html", "class_character" ],
    [ "DebugUI", "class_debug_u_i.html", null ],
    [ "DirectXTextureLoader", "class_direct_x_texture_loader.html", "class_direct_x_texture_loader" ],
    [ "EffectBase", "class_effect_base.html", "class_effect_base" ],
    [ "Enemy", "class_enemy.html", "class_enemy" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "Lesstol", "class_lesstol.html", "class_lesstol" ],
    [ "Object", "class_object.html", "class_object" ],
    [ "ObjectBackGround", "class_object_back_ground.html", "class_object_back_ground" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Renderer", "class_renderer.html", "class_renderer" ],
    [ "SceneBase", "class_scene_base.html", "class_scene_base" ],
    [ "SceneEndCard", "class_scene_end_card.html", "class_scene_end_card" ],
    [ "SceneMaingame", "class_scene_maingame.html", "class_scene_maingame" ],
    [ "SceneRoot", "class_scene_root.html", "class_scene_root" ],
    [ "SceneTitle", "class_scene_title.html", "class_scene_title" ],
    [ "SpineAnimation", "class_spine_animation.html", "class_spine_animation" ],
    [ "SpineDX11Renderer", "class_spine_d_x11_renderer.html", "class_spine_d_x11_renderer" ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", "structstbi__io__callbacks" ],
    [ "UIObject", "class_u_i_object.html", "class_u_i_object" ]
];